/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SigJNI */

#ifndef _Included_SigJNI
#define _Included_SigJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SigJNI
 * Method:    hyp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_SigJNI_hyp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     SigJNI
 * Method:    avg
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_SigJNI_avg
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     SigJNI
 * Method:    var
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_SigJNI_var
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     SigJNI
 * Method:    convolve
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_SigJNI_convolve
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
