/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    avg
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_avg
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     TestJNI
 * Method:    var
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_var
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     TestJNI
 * Method:    median
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_median
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     TestJNI
 * Method:    distance
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_distance
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     TestJNI
 * Method:    angle
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNI_angle
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
